version: '3.8'

services:
  # Seu banco de dados que já estava lá
  db:
    image: postgres:15
    container_name: nexus_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # O RabbitMQ deve estar no mesmo nível que o 'db'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: nexus_rabbitmq
    ports:
      - "5672:5672"   # Porta para o código Python
      - "15672:15672" # Porta para o Painel Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # PgAdmin também no mesmo nível
  pgadmin:
    image: dpage/pgadmin4
    container_name: nexus_pgadmin_container
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexus.com
      PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
  postgres_data: